parameters: {}
environment:
  TEXT: "${TEXT}"
  DATABASE_URL: "${DATABASE_URL}"
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        binary: false
        main: ""
        runtime: go:default
        web: true
        websecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
