parameters: {}
environment:
  TEXT: "${TEXT}"
  DATABASE_URL: "${DATABASE_URL}"
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: hello
        main: ""
        runtime: go:default

      - name: dbTest
        main: ""
        runtime: go:default

      - name: reqContext
        main: ""
        runtime: go:default
